POST http://localhost:4444/milestone
Content-Type: application/json

{
  "projectId":1,
  "mileStoneName":"마일스톤1"
}


### get
GET http://localhost:4444/milestones/1


### 삭제
DELETE http://localhost:4444/milestones/delete/1
